module.exports = {
    PAYMENT_STATUS_PAID: 'PAID',
    PAYMENT_STATUS_NOTPAID: 'NOTPAID',
    PAYMENT_STATUS_PARTPAID: 'PARTPAID',
    ORDER_STATUS_CREATED: 'CREATED',
    ORDER_STATUS_FAILED: 'FAILED',
    ORDER_STATUS_CANCELLED: 'CANCELLED',
    EXPORT_STATUS_READY: 'READY',
    EXPORT_STATUS_NOTEXPORTED: 'NOTEXPORTED',
    CONFIRMATION_STATUS_CONFIRMED: 'CONFIRMED',
    CONFIRMATION_STATUS_NOTCONFIRMED: 'NOTCONFIRMED'
};
