module.exports = {
    ADYEN_NOTIFICATION_NAME: 'adyenNotification',
    DATE_FORMAT: 'yyyyMMddhhmmssSSS',
    AMOUNT: 'amount',
    METHOD_ADYEN: 'Adyen',
    METHOD_ADYEN_POS: 'AdyenPOS',
    METHOD_ADYEN_COMPONENT: 'AdyenComponent',
    METHOD_CREDIT_CARD: 'CREDIT_CARD',

    PAYMENT_INSTRUMENT_ADYEN_CREDIT: 'ADYEN_CREDIT',
    PAYMENT_INSTRUMENT_ADYEN_POS: 'Adyen_POS',
    PAYMENT_INSTRUMENT_ADYEN_COMPONENT: 'Adyen_Component',
    SCHEME: 'scheme',
    ADYEN_METHODS: ['AdyenPOS', 'AdyenComponent', 'CREDIT_CARD'],
    ADYEN_PROCESSORS: ['Adyen_POS', 'Adyen_Component'],
    PROCESS_EVENTS: [
        'AUTHORISATION',
        'CANCELLATION',
        'CANCEL_OR_REFUND',
        'REFUND',
        'CAPTURE_FAILED',
        'ORDER_OPENED',
        'ORDER_CLOSED',
        'OFFER_CLOSED',
        'PENDING',
        'CAPTURE',
        'DONATION',
        'MANUAL_REVIEW_ACCEPT',
        'MANUAL_REVIEW_REJECT',
    ],
    UPDATE_STATUS: {
        PROCESS: 'PROCESS',
        PENDING: 'PENDING',
    },
    FRAUD_STATUS_AMBER: 'AMBER',
}