name: Deploy Storefront
on:
  pull_request:
    branches: [main, develop]
permissions:
  contents: read
env:
  NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
jobs:
  deploy-storefront:
    timeout-minutes: 30
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1
        with:
          version: 10
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - name: Install project dependencies
        run: pnpm i --ignore-scripts
      - name: Create dw.json file
        env:
          PWA_USERNAME: ${{ secrets.PWA_USERNAME }}
          PWA_PASSWORD: ${{ secrets.PWA_PASSWORD }}
          PWA_HOSTNAME: ${{ secrets.PWA_HOSTNAME }}
          PWA_CODE_VERSION: ${{ secrets.PWA_CODE_VERSION }}
        run: |
          jq -n \
            --arg username "$PWA_USERNAME" \
            --arg password "$PWA_PASSWORD" \
            --arg hostname "$PWA_HOSTNAME" \
            --arg codeVersion "$PWA_CODE_VERSION" \
            '{username:$username, password:$password, hostname:$hostname, "code-version":$codeVersion}' > dw.json
      - name: Build and upload int_adyen_PWA cartridge
        run: pnpm run buildCartridge
      - name: Install Salesforce CLI
        run: pnpm install -g sfcc-ci@2.13.0 --ignore-scripts
      - name: Zip site_import
        working-directory: ./metadata
        run: zip -r $GITHUB_WORKSPACE/site_import.zip site_import
      - name: Upload metadata
        working-directory: ./metadata
        env:
          PWA_CLIENT_ID: ${{ secrets.PWA_CLIENT_ID }}
          PWA_CLIENT_SECRET: ${{ secrets.PWA_CLIENT_SECRET }}
          PWA_HOSTNAME: ${{ secrets.PWA_HOSTNAME }}
        run: |
           sfcc-ci client:auth "$PWA_CLIENT_ID" "$PWA_CLIENT_SECRET"
           sfcc-ci instance:upload "$GITHUB_WORKSPACE/site_import.zip" -i "$PWA_HOSTNAME"
      - name: Import metadata
        working-directory: ./metadata
        env:
          PWA_HOSTNAME: ${{ secrets.PWA_HOSTNAME }}
        run: |
           sfcc-ci instance:import site_import.zip -i "$PWA_HOSTNAME" -s
      - name: Install PWA package dependencies
        working-directory: ./packages/adyen-salesforce-pwa
        run: pnpm install --ignore-scripts
      - name: Build PWA
        working-directory: ./packages/adyen-salesforce-pwa
        run: pnpm run build-prod
      - name: Pack PWA
        working-directory: ./packages/adyen-salesforce-pwa
        run: pnpm pack
      - name: Install Retail app package dependencies
        working-directory: ./packages/adyen-retail-react-app
        run: pnpm install --ignore-scripts
      - name: Install PWA in Retail app
        working-directory: ./packages/adyen-retail-react-app
        run: |
          VERSION=$(node -p "require('../adyen-salesforce-pwa/package.json').version")
          pnpm add "file:../adyen-salesforce-pwa/adyen-adyen-salesforce-pwa-${VERSION}.tgz"
      - name: Build and deploy to storefront
        working-directory: ./packages/adyen-retail-react-app
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          COMMERCE_API_CLIENT_ID: ${{ secrets.COMMERCE_API_CLIENT_ID }}
          COMMERCE_API_ORG_ID: ${{ secrets.COMMERCE_API_ORG_ID }}
          COMMERCE_API_SHORT_CODE: ${{ secrets.COMMERCE_API_SHORT_CODE }}
          COMMERCE_API_SITE_ID: ${{ secrets.COMMERCE_API_SITE_ID }}
          COMMERCE_API_DEFAULT_SITE: ${{ secrets.COMMERCE_API_DEFAULT_SITE }}
          SCAPI_URL: ${{ secrets.SCAPI_URL }}
          OCAPI_URL: ${{ secrets.OCAPI_URL }}
          ENVIRONMENT_ID: ${{ secrets.ENVIRONMENT_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          COMMERCE_API_CLIENT_ID_PRIVATE: ${{ secrets.COMMERCE_API_CLIENT_ID_PRIVATE }}
          COMMERCE_API_CLIENT_SECRET: ${{ secrets.COMMERCE_API_CLIENT_SECRET }}
          MRT_PROJECT_SLUG: ${{ secrets.MRT_PROJECT_SLUG }}
          MRT_DEPLOY_TARGET: ${{ secrets.MRT_DEPLOY_TARGET }}
          MRT_USER: ${{ secrets.MRT_USER }}
          MRT_API_KEY: ${{ secrets.MRT_API_KEY }}
        run: pnpm run push  -s "$MRT_PROJECT_SLUG" -t "$MRT_DEPLOY_TARGET" --user "$MRT_USER" --key "$MRT_API_KEY" -m "$BRANCH_NAME"