name: E2E Tests with Playwright
on:
  pull_request:
    branches: [main, develop]
permissions:
  contents: read
jobs:
  build-and-test:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    timeout-minutes: 10
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1
        with:
          version: 10
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
      - name: Install project dependencies
        run: pnpm install --ignore-scripts
      - name: Install PWA package dependencies
        working-directory: ./packages/adyen-salesforce-pwa
        run: pnpm install --ignore-scripts
      - name: Build PWA
        working-directory: ./packages/adyen-salesforce-pwa
        run: pnpm run build-dev
      - name: Pack PWA package
        working-directory: ./packages/adyen-salesforce-pwa
        run: pnpm pack
      - name: Install Retail app package dependencies
        working-directory: ./packages/adyen-retail-react-app
        run: pnpm install --ignore-scripts
      - name: Install PWA in Retail app
        working-directory: ./packages/adyen-retail-react-app
        run: |
          VERSION=$(node -p "require('../adyen-salesforce-pwa/package.json').version")
          pnpm add "file:../adyen-salesforce-pwa/adyen-adyen-salesforce-pwa-${VERSION}.tgz"
      - name: Install Playwright dependencies
        working-directory: ./packages/e2e-tests
        run: pnpm install --ignore-scripts
      - name: Install Playwright Browsers
        working-directory: ./packages/e2e-tests
        run: pnpm exec playwright install --with-deps
      - name: Start Webserver & Run Playwright tests
        working-directory: ./packages/e2e-tests
        run: pnpm run test
        env:
          RefArch_ADYEN_API_KEY: ${{secrets.ADYEN_API_KEY}}
          RefArch_ADYEN_MERCHANT_ACCOUNT: ${{secrets.ADYEN_MERCHANT_ACCOUNT}}
          RefArch_ADYEN_CLIENT_KEY: ${{secrets.ADYEN_CLIENT_KEY}}
          RefArch_ADYEN_ENVIRONMENT: ${{secrets.ADYEN_ENVIRONMENT}}
          RefArch_ADYEN_WEBHOOK_USER: ${{ secrets.ADYEN_WEBHOOK_USER }}
          RefArch_ADYEN_WEBHOOK_PASSWORD: ${{ secrets.ADYEN_WEBHOOK_PASSWORD }}
          RefArch_ADYEN_HMAC_KEY: ${{ secrets.ADYEN_HMAC_KEY }}
          SYSTEM_INTEGRATOR_NAME: ${{ secrets.SYSTEM_INTEGRATOR_NAME }}
          COMMERCE_API_CLIENT_ID: ${{ secrets.COMMERCE_API_CLIENT_ID }}
          COMMERCE_API_ORG_ID: ${{ secrets.COMMERCE_API_ORG_ID }}
          COMMERCE_API_SHORT_CODE: ${{ secrets.COMMERCE_API_SHORT_CODE }}
          COMMERCE_API_SITE_ID: ${{ secrets.COMMERCE_API_SITE_ID }}
          COMMERCE_API_DEFAULT_SITE: ${{ secrets.COMMERCE_API_DEFAULT_SITE }}
          SCAPI_URL: ${{ secrets.SCAPI_URL }}
          OCAPI_URL: ${{ secrets.OCAPI_URL }}
          ENVIRONMENT_ID: ${{ secrets.ENVIRONMENT_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          COMMERCE_API_CLIENT_ID_PRIVATE: ${{ secrets.COMMERCE_API_CLIENT_ID_PRIVATE }}
          COMMERCE_API_CLIENT_SECRET: ${{ secrets.COMMERCE_API_CLIENT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          E2E_PAYPAL_USERNAME: ${{secrets.E2E_PAYPAL_USERNAME}}
          E2E_PAYPAL_PASSWORD: ${{secrets.E2E_PAYPAL_PASSWORD}}
          SFCC_REALM_ID: ${{ secrets.SFCC_REALM_ID }}
          SFCC_INSTANCE_ID: ${{ secrets.SFCC_INSTANCE_ID }}
          SFCC_OAUTH_SCOPES: ${{ secrets.SFCC_OAUTH_SCOPES }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: playwright-report
          path: ./packages/e2e-tests/playwright-report/
          retention-days: 30